const productos = [
  {
    id: 1,
    nombre: 'Leche',
    valor: 2500,
    fechaVencimiento: '2024-01-10',
    categoria: 'Lácteos',
    descripcion: 'Leche deslactosada 1L',
  },
  {
    id: 2,
    nombre: 'Pan',
    valor: 3000,
    fechaVencimiento: '2023-05-20',
    categoria: 'Panadería',
    descripcion: 'Pan integral 500g',
  },
  {
    id: 3,
    nombre: 'Queso',
    valor: 4500,
    fechaVencimiento: '2024-03-15',
    categoria: 'Lácteos',
    descripcion: 'Queso fresco 250g',
  },
  {
    id: 4,
    nombre: 'Yogur',
    valor: 2000,
    fechaVencimiento: '2024-02-10',
    categoria: 'Lácteos',
    descripcion: 'Yogur natural 500ml',
  },
  {
    id: 5,
    nombre: 'Manzanas',
    valor: 5000,
    fechaVencimiento: '2023-05-30',
    categoria: 'Frutas',
    descripcion: 'Manzanas rojas paquete de 6',
  },
  {
    id: 6,
    nombre: 'Bananas',
    valor: 3800,
    fechaVencimiento: '2023-05-25',
    categoria: 'Frutas',
    descripcion: 'Bananas orgánicas paquete de 12',
  },
  {
    id: 7,
    nombre: 'Zanahorias',
    valor: 3200,
    fechaVencimiento: '2023-06-15',
    categoria: 'Verduras',
    descripcion: 'Zanahorias baby paquete 500g',
  },
  {
    id: 8,
    nombre: 'Tomates',
    valor: 3600,
    fechaVencimiento: '2023-06-20',
    categoria: 'Verduras',
    descripcion: 'Tomates cherry paquete 500g',
  },
  {
    id: 9,
    nombre: 'Pollo',
    valor: 15000,
    fechaVencimiento: '2024-01-05',
    categoria: 'Carnes',
    descripcion: 'Pechuga de pollo 1kg',
  },
  {
    id: 10,
    nombre: 'Carne de res',
    valor: 18000,
    fechaVencimiento: '2024-01-15',
    categoria: 'Carnes',
    descripcion: 'Carne de res para asar 1kg',
  },
  {
    id: 11,
    nombre: 'Cerveza',
    valor: 22000,
    fechaVencimiento: '2024-07-01',
    categoria: 'Bebidas',
    descripcion: 'Pack de cerveza 6 unidades',
  },
  {
    id: 12,
    nombre: 'Vino',
    valor: 30000,
    fechaVencimiento: '2025-12-31',
    categoria: 'Bebidas',
    descripcion: 'Vino tinto reserva 750ml',
  },
  {
    id: 13,
    nombre: 'Pasta',
    valor: 2300,
    fechaVencimiento: '2024-08-25',
    categoria: 'Pasta',
    descripcion: 'Pasta de trigo 500g',
  },
  {
    id: 14,
    nombre: 'Arroz',
    valor: 2600,
    fechaVencimiento: '2024-09-10',
    categoria: 'Granos',
    descripcion: 'Arroz blanco 1kg',
  },
  {
    id: 15,
    nombre: 'Lentejas',
    valor: 2900,
    fechaVencimiento: '2024-10-05',
    categoria: 'Granos',
    descripcion: 'Lentejas paquete 500g',
  },
]

const automoviles = [
  {
    id: 1,
    marca: 'Toyota',
    cilindraje: 1800,
    tipo: 'Híbrido',
    linea: 'Prius',
    color: 'Rojo',
    placa: 'ABC123',
    valor: '150000000',
  },
  {
    id: 2,
    marca: 'Tesla',
    cilindraje: 0,
    tipo: 'Eléctrico',
    linea: 'Model 3',
    color: 'Negro',
    placa: 'DEF456',
    valor: '250000000 ',
  },
  {
    id: 3,
    marca: 'Honda',
    cilindraje: 1500,
    tipo: 'Híbrido',
    linea: 'Civic',
    color: 'Azul',
    placa: 'GHI789',
    valor: '100000000',
  },
  {
    id: 4,
    marca: 'Chevrolet',
    cilindraje: 1600,
    tipo: 'Gasolina',
    linea: 'Cruze',
    color: 'Blanco',
    placa: 'JKL012',
    valor: '50000000',
  },
  {
    id: 5,
    marca: 'Ford',
    cilindraje: 2500,
    tipo: 'Gasolina',
    linea: 'Mustang',
    color: 'Amarillo',
    placa: 'MNO345',
    valor: '270000000',
  },
  {
    id: 6,
    marca: 'Nissan',
    cilindraje: 2000,
    tipo: 'Eléctrico',
    linea: 'Leaf',
    color: 'Verde',
    placa: 'PQR678',
    valor: '167000000',
  },
  {
    id: 7,
    marca: 'BMW',
    cilindraje: 3000,
    tipo: 'Híbrido',
    linea: 'i8',
    color: 'Negro',
    placa: 'STU901',
    valor: '300000000',
  },
  {
    id: 8,
    marca: 'Mercedes',
    cilindraje: 3500,
    tipo: 'Gasolina',
    linea: 'Class C',
    color: 'Gris',
    placa: 'VWX234',
    valor: '260000000',
  },
  {
    id: 9,
    marca: 'Audi',
    cilindraje: 2200,
    tipo: 'Híbrido',
    linea: 'A3',
    color: 'Rojo',
    placa: 'YZA567',
    valor: '185000000',
  },
  {
    id: 10,
    marca: 'Volkswagen',
    cilindraje: 1400,
    tipo: 'Gasolina',
    linea: 'Golf',
    color: 'Azul',
    placa: 'BCD890',
    valor: '150000000',
  },
  {
    id: 11,
    marca: 'Hyundai',
    cilindraje: 1600,
    tipo: 'Eléctrico',
    linea: 'Ioniq',
    color: 'Blanco',
    placa: 'EFG123',
    valor: '120000000',
  },
  {
    id: 12,
    marca: 'Kia',
    cilindraje: 1300,
    tipo: 'Gasolina',
    linea: 'Rio',
    color: 'Negro',
    placa: 'HIJ456',
    valor: '75000000',
  },
  {
    id: 13,
    marca: 'Peugeot',
    cilindraje: 1800,
    tipo: 'Gasolina',
    linea: '208',
    color: 'Amarillo',
    placa: 'KLM789',
    valor: '99000000',
  },
  {
    id: 14,
    marca: 'Renault',
    cilindraje: 1200,
    tipo: 'Híbrido',
    linea: 'Clio',
    color: 'Verde',
    placa: 'NOP012',
    valor: '110000000',
  },
  {
    id: 15,
    marca: 'Fiat',
    cilindraje: 1100,
    tipo: 'Gasolina',
    linea: '500',
    color: 'Rojo',
    placa: 'QRS345',
    valor: '115000000',
  },
]
module.exports = { productos, automoviles }
